# TODO: Go here for detailed information on Application Service configuration:
#       https://docs.edgexfoundry.org/latest/microservices/application/GeneralAppServiceConfig/
[Writable]
LogLevel = "INFO"

  [Writable.InsecureSecrets]
    # TODO: Remove if not using HTTPS Webserver
    [Writable.InsecureSecrets.HTTPS]
    path = "https"
      [Writable.InsecureSecrets.HTTPS.Secrets]
      cert = ""
      key = ""

  [Writable.Telemetry]
    [Writable.Telemetry.Metrics] # All service's metric private configuration metrics must be listed here.
    # TODO: Remove sample custom metric and implement meaningful custom metrics if any needed.
    # Custom App Service Metrics
    EventsConvertedToXML = true

[Service]
# TODO: set this port appropriately,
#       App service use port assignments 597xx with lower range 00-39 reserved for
#       app-service-configurable profiles/instances, Rules Engine and examples
Port = 59740
StartupMsg = "app-new-service Application Service has started"

# TODO: Remove section if not using HTTPS Webserver. Default protocol is HTTP if section is empty
[HttpServer]
Protocol = "http"
SecretName = "https"
HTTPSCertName = "cert"
HTTPSKeyName = "key"

[Clients]
  [Clients.core-data]
  Protocol = "http"
  Host = "localhost"
  Port = 59880


  [Clients.core-command]
  #  Protocol = "http"
  #  Host = "localhost"
  #  Port = 59882
  # Choose to use new messaging based communication for Command Client.
  # Only valid if MessageBus Trigger is used
  # If prefer REST, remove below and uncomment above
  UseMessageBus = true
  [Clients.core-command.Topics]
  CommandQueryRequestTopicPrefix = "edgex/core/commandquery/request"
  CommandRequestTopicPrefix = "edgex/core/command/request"
  ResponseTopicPrefix = "edgex/response"

[Clients.support-notifications]
  Protocol = "http"
  Host = "localhost"
  Port = 59860

[MessageBus]
Disabled = false  # TODO: set to true if not using edgex-messagebus Trigger below and don't want Metrics or Commands via MessageBus
  [MessageBus.Topics]
  SubscribeTopics = "edgex/events/#"
  PublishTopic="event-xml"
  [MessageBus.Optional]
  # Default MQTT Specific options that need to be here to enable environment variable overrides of them
  ClientId ="app-new-service"

# TODO: If using mqtt messagebus, Uncomment this section and remove above [MessageBus] section,
#       Otherwise remove this commented out block
#[MessageBus]
#Protocol = "tcp"
#Host = "localhost"
#Port = 1883
#Type = "mqtt"
#AuthMode = "none"  # required for redis messagebus (secure or insecure).
#SecretName = "mqtt-bus"
#  [MessageBus.Topics]
#  SubscribeTopics = "edgex/events/#"
#  PublishTopic="event-xml"
#  [MessageBus.Optional]
#  ClientId ="app-new-service"
#  Qos =  "0" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
#  KeepAlive = "10" # Seconds (must be 2 or greater)
#  Retained = "false"
#  AutoReconnect = "true"
#  ConnectTimeout = "5" # Seconds
#  SkipCertVerify = "false"

[Trigger]
# Note that the MessaegBus connection above is used by edgex-messagebus trigger
Type="edgex-messagebus"

# TODO: Add custom settings needed by your app service or remove if you don't have any settings.
# This can be any Key/Value pair you need.
# For more details see: https://docs.edgexfoundry.org/latest/microservices/application/GeneralAppServiceConfig/#application-settings
# Example that works with devices from the Virtual Device service:
[ApplicationSettings]
DeviceNames = "Random-Boolean-Device, Random-Integer-Device, Random-UnsignedInteger-Device, Random-Float-Device, Random-Binary-Device, sample-numeric"

# TODO: Replace this section with your actual structured custom configuration section
#       or remove if you don't have a need for structured custom configuration
# This can be any structure you need, but it can not contain slices. Use a maps instead of slices.
# For more details see: https://docs.edgexfoundry.org/latest/microservices/application/GeneralAppServiceConfig/#custom-configuration
[AppCustom]
ResourceNames = "Boolean, Int32, Uint32, Float32, Binary, Switch"
SomeValue = 123
  [AppCustom.SomeService]
  Host = "localhost"
  Port = 9080
  Protocol = "http"
